# frozen_string_literal: true

# Stores precomputed duplicate person suggestions.
# Generated by ComputeDuplicatesJob, which runs nightly.
# Pairs are stored with smaller person_id first to avoid duplicates.
class DuplicateSuggestion < ApplicationRecord
  belongs_to :person
  belongs_to :duplicate_person, class_name: "Person"

  enum :match_type, { exact: "exact", similar: "similar" }

  validates :person_id, comparison: { less_than: :duplicate_person_id }
  validates :person_id, uniqueness: { scope: :duplicate_person_id }

  # Get all suggestions involving a person (either side)
  scope :involving, ->(person) {
    person_id = person.is_a?(Person) ? person.id : person
    where(person_id: person_id).or(where(duplicate_person_id: person_id))
  }

  # Get the "other" person in this pair
  def other_person(from_person)
    from_id = from_person.is_a?(Person) ? from_person.id : from_person
    person_id == from_id ? duplicate_person : person
  end

  # Timestamp of most recent computation
  def self.last_computed_at
    maximum(:created_at)
  end
end
